application: mindcyclone
version: 0-0-1
runtime: python
api_version: 1
skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (.*/\.svn/.*)|
 (.*/Thumbs\.db)|
 )$
 
handlers:
- url: /static
  static_dir: static
  
- url: /rte
  static_dir: rte
  
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  mime_type: image/x-icon
  
- url: /.*
  script: app/main.py
